### ISSUE TITLE
ESLint error on import

### ISSUE THREAD

**Issue by stevezau** [Nehorim/async-retry-decorator#3]
Hi, thanks for this lib.

When trying to import i get an ESLint error. I think because this is missing an index.js? What's the correct way to import?

![image](https://user-images.githubusercontent.com/6075483/76721737-19459500-6795-11ea-8608-afab8ba695bb.png)

**Comment by pchouzenoux** [comment]
Hello, thanks for you feedbacks.

I fixed that in the new version [v1.2.1](https://github.com/Nehorim/async-retry-decorator/releases/tag/v1.2.1).

Let me know if you still have some trouble.
